#==============================================================================
# Hierarchical dofile generated by Conformal LEC
# Version: 20.10-p100 (01-May-2020) (64 bit executable)
#------------------------------------------------------------------------------
# For additional reporting on 'not written' modules, see the 'VERBOSE REPORTING'
# section at the end of the hierarchical dofile
#------------------------------------------------------------------------------
# The command 'set module property' sets the instance context for the current
# root module. It is intended only for hierarchical comparison, and should
# not be modified by the user.
#------------------------------------------------------------------------------
# TERMS AND NOTATIONS USED
#------------------------------------------------------------------------------
# Module Instantiation Ratio: Average number of instantiations per matching module
# Periphery size: #Logic gates in the fanin and fanout cone of instance's input and output boundary, and bounded by key-points
# 0: Indicates pin is constant zero
# 1: Indicates pin is constant one
# X: Indicates pin is full DC
# U: Indicates pin is unreachable
# Z: Indicates pin is floating
# KP<--: Indicates pin's fanin is directly connected to key-point (ignores buffers/inverters)
# -->KP: Indicates pin's fanout is directly connected to key-point (ignores buffers/inverters)
# REP: Indicates pin is representative pin
# EQ_REP: <polarity> rep_pinname>: Indicates pin is a member EQ pin with
# 'rep_pinname' specifying the representative, and 'polarity' specifying
# if it is positive or negative equivalent
# = : Indicates that the pins on LHS and RHS are mapped
# + : Indicates positive polarity for pin mapping
# - : Indicates negative polarity for pin mapping
# ? : Indicates unknown polarity for pin mapping
# G: Indicates that the pin belongs to Golden
# R: Indicates that the pin belongs to Revised
# IN: Indicates that the pin is an Input pin
# OUT: Indicates that the pin is an Output pin
# IO: Indicates that the pin is an Inout pin. Polarity of Inout pin is
#     always '?' because of name-only mapping
#==============================================================================

set_system_mode setup
# Root Modules
# Comparing
#-------------------------------------------------------------------------------
# MODULE picorv32 (G) INSTANCE / (G)
# MODULE picorv32 (R) INSTANCE / (R)
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk (REP)  =   (R) clk (REP) (by name)
# IN (G) resetn (REP)  =   (R) resetn (REP) (by name)
# IN (G) mem_ready (REP)  =   (R) mem_ready (REP) (by name)
# IN (G) mem_rdata[31] (REP)  =   (R) mem_rdata[31] (REP) (by name)
# IN (G) mem_rdata[30] (REP)  =   (R) mem_rdata[30] (REP) (by name)
# IN (G) mem_rdata[29] (REP)  =   (R) mem_rdata[29] (REP) (by name)
# IN (G) mem_rdata[28] (REP)  =   (R) mem_rdata[28] (REP) (by name)
# IN (G) mem_rdata[27] (REP)  =   (R) mem_rdata[27] (REP) (by name)
# IN (G) mem_rdata[26] (REP)  =   (R) mem_rdata[26] (REP) (by name)
# IN (G) mem_rdata[25] (REP)  =   (R) mem_rdata[25] (REP) (by name)
# IN (G) mem_rdata[24] (REP)  =   (R) mem_rdata[24] (REP) (by name)
# IN (G) mem_rdata[23] (REP)  =   (R) mem_rdata[23] (REP) (by name)
# IN (G) mem_rdata[22] (REP)  =   (R) mem_rdata[22] (REP) (by name)
# IN (G) mem_rdata[21] (REP)  =   (R) mem_rdata[21] (REP) (by name)
# IN (G) mem_rdata[20] (REP)  =   (R) mem_rdata[20] (REP) (by name)
# IN (G) mem_rdata[19] (REP)  =   (R) mem_rdata[19] (REP) (by name)
# IN (G) mem_rdata[18] (REP)  =   (R) mem_rdata[18] (REP) (by name)
# IN (G) mem_rdata[17] (REP)  =   (R) mem_rdata[17] (REP) (by name)
# IN (G) mem_rdata[16] (REP)  =   (R) mem_rdata[16] (REP) (by name)
# IN (G) mem_rdata[15] (REP)  =   (R) mem_rdata[15] (REP) (by name)
# IN (G) mem_rdata[14] (REP)  =   (R) mem_rdata[14] (REP) (by name)
# IN (G) mem_rdata[13] (REP)  =   (R) mem_rdata[13] (REP) (by name)
# IN (G) mem_rdata[12] (REP)  =   (R) mem_rdata[12] (REP) (by name)
# IN (G) mem_rdata[11] (REP)  =   (R) mem_rdata[11] (REP) (by name)
# IN (G) mem_rdata[10] (REP)  =   (R) mem_rdata[10] (REP) (by name)
# IN (G) mem_rdata[9] (REP)  =   (R) mem_rdata[9] (REP) (by name)
# IN (G) mem_rdata[8] (REP)  =   (R) mem_rdata[8] (REP) (by name)
# IN (G) mem_rdata[7] (REP)  =   (R) mem_rdata[7] (REP) (by name)
# IN (G) mem_rdata[6] (REP)  =   (R) mem_rdata[6] (REP) (by name)
# IN (G) mem_rdata[5] (REP)  =   (R) mem_rdata[5] (REP) (by name)
# IN (G) mem_rdata[4] (REP)  =   (R) mem_rdata[4] (REP) (by name)
# IN (G) mem_rdata[3] (REP)  =   (R) mem_rdata[3] (REP) (by name)
# IN (G) mem_rdata[2] (REP)  =   (R) mem_rdata[2] (REP) (by name)
# IN (G) mem_rdata[1] (REP)  =   (R) mem_rdata[1] (REP) (by name)
# IN (G) mem_rdata[0] (REP)  =   (R) mem_rdata[0] (REP) (by name)
# IN (G) pcpi_wr U(REP)  =   (R) pcpi_wr U(REP) (by name)
# IN (G) pcpi_rd[31] U(REP)  =   (R) pcpi_rd[31] U(REP) (by name)
# IN (G) pcpi_rd[30] U(REP)  =   (R) pcpi_rd[30] U(REP) (by name)
# IN (G) pcpi_rd[29] U(REP)  =   (R) pcpi_rd[29] U(REP) (by name)
# IN (G) pcpi_rd[28] U(REP)  =   (R) pcpi_rd[28] U(REP) (by name)
# IN (G) pcpi_rd[27] U(REP)  =   (R) pcpi_rd[27] U(REP) (by name)
# IN (G) pcpi_rd[26] U(REP)  =   (R) pcpi_rd[26] U(REP) (by name)
# IN (G) pcpi_rd[25] U(REP)  =   (R) pcpi_rd[25] U(REP) (by name)
# IN (G) pcpi_rd[24] U(REP)  =   (R) pcpi_rd[24] U(REP) (by name)
# IN (G) pcpi_rd[23] U(REP)  =   (R) pcpi_rd[23] U(REP) (by name)
# IN (G) pcpi_rd[22] U(REP)  =   (R) pcpi_rd[22] U(REP) (by name)
# IN (G) pcpi_rd[21] U(REP)  =   (R) pcpi_rd[21] U(REP) (by name)
# IN (G) pcpi_rd[20] U(REP)  =   (R) pcpi_rd[20] U(REP) (by name)
# IN (G) pcpi_rd[19] U(REP)  =   (R) pcpi_rd[19] U(REP) (by name)
# IN (G) pcpi_rd[18] U(REP)  =   (R) pcpi_rd[18] U(REP) (by name)
# IN (G) pcpi_rd[17] U(REP)  =   (R) pcpi_rd[17] U(REP) (by name)
# IN (G) pcpi_rd[16] U(REP)  =   (R) pcpi_rd[16] U(REP) (by name)
# IN (G) pcpi_rd[15] U(REP)  =   (R) pcpi_rd[15] U(REP) (by name)
# IN (G) pcpi_rd[14] U(REP)  =   (R) pcpi_rd[14] U(REP) (by name)
# IN (G) pcpi_rd[13] U(REP)  =   (R) pcpi_rd[13] U(REP) (by name)
# IN (G) pcpi_rd[12] U(REP)  =   (R) pcpi_rd[12] U(REP) (by name)
# IN (G) pcpi_rd[11] U(REP)  =   (R) pcpi_rd[11] U(REP) (by name)
# IN (G) pcpi_rd[10] U(REP)  =   (R) pcpi_rd[10] U(REP) (by name)
# IN (G) pcpi_rd[9] U(REP)  =   (R) pcpi_rd[9] U(REP) (by name)
# IN (G) pcpi_rd[8] U(REP)  =   (R) pcpi_rd[8] U(REP) (by name)
# IN (G) pcpi_rd[7] U(REP)  =   (R) pcpi_rd[7] U(REP) (by name)
# IN (G) pcpi_rd[6] U(REP)  =   (R) pcpi_rd[6] U(REP) (by name)
# IN (G) pcpi_rd[5] U(REP)  =   (R) pcpi_rd[5] U(REP) (by name)
# IN (G) pcpi_rd[4] U(REP)  =   (R) pcpi_rd[4] U(REP) (by name)
# IN (G) pcpi_rd[3] U(REP)  =   (R) pcpi_rd[3] U(REP) (by name)
# IN (G) pcpi_rd[2] U(REP)  =   (R) pcpi_rd[2] U(REP) (by name)
# IN (G) pcpi_rd[1] U(REP)  =   (R) pcpi_rd[1] U(REP) (by name)
# IN (G) pcpi_rd[0] U(REP)  =   (R) pcpi_rd[0] U(REP) (by name)
# IN (G) pcpi_wait U(REP)  =   (R) pcpi_wait U(REP) (by name)
# IN (G) pcpi_ready U(REP)  =   (R) pcpi_ready U(REP) (by name)
# IN (G) irq[31] U(REP)  =   (R) irq[31] U(REP) (by name)
# IN (G) irq[30] U(REP)  =   (R) irq[30] U(REP) (by name)
# IN (G) irq[29] U(REP)  =   (R) irq[29] U(REP) (by name)
# IN (G) irq[28] U(REP)  =   (R) irq[28] U(REP) (by name)
# IN (G) irq[27] U(REP)  =   (R) irq[27] U(REP) (by name)
# IN (G) irq[26] U(REP)  =   (R) irq[26] U(REP) (by name)
# IN (G) irq[25] U(REP)  =   (R) irq[25] U(REP) (by name)
# IN (G) irq[24] U(REP)  =   (R) irq[24] U(REP) (by name)
# IN (G) irq[23] U(REP)  =   (R) irq[23] U(REP) (by name)
# IN (G) irq[22] U(REP)  =   (R) irq[22] U(REP) (by name)
# IN (G) irq[21] U(REP)  =   (R) irq[21] U(REP) (by name)
# IN (G) irq[20] U(REP)  =   (R) irq[20] U(REP) (by name)
# IN (G) irq[19] U(REP)  =   (R) irq[19] U(REP) (by name)
# IN (G) irq[18] U(REP)  =   (R) irq[18] U(REP) (by name)
# IN (G) irq[17] U(REP)  =   (R) irq[17] U(REP) (by name)
# IN (G) irq[16] U(REP)  =   (R) irq[16] U(REP) (by name)
# IN (G) irq[15] U(REP)  =   (R) irq[15] U(REP) (by name)
# IN (G) irq[14] U(REP)  =   (R) irq[14] U(REP) (by name)
# IN (G) irq[13] U(REP)  =   (R) irq[13] U(REP) (by name)
# IN (G) irq[12] U(REP)  =   (R) irq[12] U(REP) (by name)
# IN (G) irq[11] U(REP)  =   (R) irq[11] U(REP) (by name)
# IN (G) irq[10] U(REP)  =   (R) irq[10] U(REP) (by name)
# IN (G) irq[9] U(REP)  =   (R) irq[9] U(REP) (by name)
# IN (G) irq[8] U(REP)  =   (R) irq[8] U(REP) (by name)
# IN (G) irq[7] U(REP)  =   (R) irq[7] U(REP) (by name)
# IN (G) irq[6] U(REP)  =   (R) irq[6] U(REP) (by name)
# IN (G) irq[5] U(REP)  =   (R) irq[5] U(REP) (by name)
# IN (G) irq[4] U(REP)  =   (R) irq[4] U(REP) (by name)
# IN (G) irq[3] U(REP)  =   (R) irq[3] U(REP) (by name)
# IN (G) irq[2] U(REP)  =   (R) irq[2] U(REP) (by name)
# IN (G) irq[1] U(REP)  =   (R) irq[1] U(REP) (by name)
# IN (G) irq[0] U(REP)  =   (R) irq[0] U(REP) (by name)
# RESOLVED Constraints
# OUT (G) trap (REP)  =   (R) trap (REP) (by name)
# OUT (G) mem_valid (REP)  =   (R) mem_valid (REP) (by name)
# OUT (G) mem_instr (REP)  =   (R) mem_instr (REP) (by name)
# OUT (G) mem_addr[31] (REP)  =   (R) mem_addr[31] (REP) (by name)
# OUT (G) mem_addr[30] (REP)  =   (R) mem_addr[30] (REP) (by name)
# OUT (G) mem_addr[29] (REP)  =   (R) mem_addr[29] (REP) (by name)
# OUT (G) mem_addr[28] (REP)  =   (R) mem_addr[28] (REP) (by name)
# OUT (G) mem_addr[27] (REP)  =   (R) mem_addr[27] (REP) (by name)
# OUT (G) mem_addr[26] (REP)  =   (R) mem_addr[26] (REP) (by name)
# OUT (G) mem_addr[25] (REP)  =   (R) mem_addr[25] (REP) (by name)
# OUT (G) mem_addr[24] (REP)  =   (R) mem_addr[24] (REP) (by name)
# OUT (G) mem_addr[23] (REP)  =   (R) mem_addr[23] (REP) (by name)
# OUT (G) mem_addr[22] (REP)  =   (R) mem_addr[22] (REP) (by name)
# OUT (G) mem_addr[21] (REP)  =   (R) mem_addr[21] (REP) (by name)
# OUT (G) mem_addr[20] (REP)  =   (R) mem_addr[20] (REP) (by name)
# OUT (G) mem_addr[19] (REP)  =   (R) mem_addr[19] (REP) (by name)
# OUT (G) mem_addr[18] (REP)  =   (R) mem_addr[18] (REP) (by name)
# OUT (G) mem_addr[17] (REP)  =   (R) mem_addr[17] (REP) (by name)
# OUT (G) mem_addr[16] (REP)  =   (R) mem_addr[16] (REP) (by name)
# OUT (G) mem_addr[15] (REP)  =   (R) mem_addr[15] (REP) (by name)
# OUT (G) mem_addr[14] (REP)  =   (R) mem_addr[14] (REP) (by name)
# OUT (G) mem_addr[13] (REP)  =   (R) mem_addr[13] (REP) (by name)
# OUT (G) mem_addr[12] (REP)  =   (R) mem_addr[12] (REP) (by name)
# OUT (G) mem_addr[11] (REP)  =   (R) mem_addr[11] (REP) (by name)
# OUT (G) mem_addr[10] (REP)  =   (R) mem_addr[10] (REP) (by name)
# OUT (G) mem_addr[9] (REP)  =   (R) mem_addr[9] (REP) (by name)
# OUT (G) mem_addr[8] (REP)  =   (R) mem_addr[8] (REP) (by name)
# OUT (G) mem_addr[7] (REP)  =   (R) mem_addr[7] (REP) (by name)
# OUT (G) mem_addr[6] (REP)  =   (R) mem_addr[6] (REP) (by name)
# OUT (G) mem_addr[5] (REP)  =   (R) mem_addr[5] (REP) (by name)
# OUT (G) mem_addr[4] (REP)  =   (R) mem_addr[4] (REP) (by name)
# OUT (G) mem_addr[3] (REP)  =   (R) mem_addr[3] (REP) (by name)
# OUT (G) mem_addr[2] (REP)  =   (R) mem_addr[2] (REP) (by name)
# OUT (G) mem_addr[1] 0(REP)  =   (R) mem_addr[1] 0(REP) (by name)
# OUT (G) mem_addr[0] 0(REP)  =   (R) mem_addr[0] 0(REP) (by name)
# OUT (G) mem_wdata[31] (REP)  =   (R) mem_wdata[31] (REP) (by name)
# OUT (G) mem_wdata[30] (REP)  =   (R) mem_wdata[30] (REP) (by name)
# OUT (G) mem_wdata[29] (REP)  =   (R) mem_wdata[29] (REP) (by name)
# OUT (G) mem_wdata[28] (REP)  =   (R) mem_wdata[28] (REP) (by name)
# OUT (G) mem_wdata[27] (REP)  =   (R) mem_wdata[27] (REP) (by name)
# OUT (G) mem_wdata[26] (REP)  =   (R) mem_wdata[26] (REP) (by name)
# OUT (G) mem_wdata[25] (REP)  =   (R) mem_wdata[25] (REP) (by name)
# OUT (G) mem_wdata[24] (REP)  =   (R) mem_wdata[24] (REP) (by name)
# OUT (G) mem_wdata[23] (REP)  =   (R) mem_wdata[23] (REP) (by name)
# OUT (G) mem_wdata[22] (REP)  =   (R) mem_wdata[22] (REP) (by name)
# OUT (G) mem_wdata[21] (REP)  =   (R) mem_wdata[21] (REP) (by name)
# OUT (G) mem_wdata[20] (REP)  =   (R) mem_wdata[20] (REP) (by name)
# OUT (G) mem_wdata[19] (REP)  =   (R) mem_wdata[19] (REP) (by name)
# OUT (G) mem_wdata[18] (REP)  =   (R) mem_wdata[18] (REP) (by name)
# OUT (G) mem_wdata[17] (REP)  =   (R) mem_wdata[17] (REP) (by name)
# OUT (G) mem_wdata[16] (REP)  =   (R) mem_wdata[16] (REP) (by name)
# OUT (G) mem_wdata[15] (REP)  =   (R) mem_wdata[15] (REP) (by name)
# OUT (G) mem_wdata[14] (REP)  =   (R) mem_wdata[14] (REP) (by name)
# OUT (G) mem_wdata[13] (REP)  =   (R) mem_wdata[13] (REP) (by name)
# OUT (G) mem_wdata[12] (REP)  =   (R) mem_wdata[12] (REP) (by name)
# OUT (G) mem_wdata[11] (REP)  =   (R) mem_wdata[11] (REP) (by name)
# OUT (G) mem_wdata[10] (REP)  =   (R) mem_wdata[10] (REP) (by name)
# OUT (G) mem_wdata[9] (REP)  =   (R) mem_wdata[9] (REP) (by name)
# OUT (G) mem_wdata[8] (REP)  =   (R) mem_wdata[8] (REP) (by name)
# OUT (G) mem_wdata[7] (REP)  =   (R) mem_wdata[7] (REP) (by name)
# OUT (G) mem_wdata[6] (REP)  =   (R) mem_wdata[6] (REP) (by name)
# OUT (G) mem_wdata[5] (REP)  =   (R) mem_wdata[5] (REP) (by name)
# OUT (G) mem_wdata[4] (REP)  =   (R) mem_wdata[4] (REP) (by name)
# OUT (G) mem_wdata[3] (REP)  =   (R) mem_wdata[3] (REP) (by name)
# OUT (G) mem_wdata[2] (REP)  =   (R) mem_wdata[2] (REP) (by name)
# OUT (G) mem_wdata[1] (REP)  =   (R) mem_wdata[1] (REP) (by name)
# OUT (G) mem_wdata[0] (REP)  =   (R) mem_wdata[0] (REP) (by name)
# OUT (G) mem_wstrb[3] (REP)  =   (R) mem_wstrb[3] (REP) (by name)
# OUT (G) mem_wstrb[2] (REP)  =   (R) mem_wstrb[2] (REP) (by name)
# OUT (G) mem_wstrb[1] (REP)  =   (R) mem_wstrb[1] (REP) (by name)
# OUT (G) mem_wstrb[0] (REP)  =   (R) mem_wstrb[0] (REP) (by name)
# OUT (G) mem_la_read (REP)  =   (R) mem_la_read (REP) (by name)
# OUT (G) mem_la_write (REP)  =   (R) mem_la_write (REP) (by name)
# OUT (G) mem_la_addr[31] (REP)  =   (R) mem_la_addr[31] (REP) (by name)
# OUT (G) mem_la_addr[30] (REP)  =   (R) mem_la_addr[30] (REP) (by name)
# OUT (G) mem_la_addr[29] (REP)  =   (R) mem_la_addr[29] (REP) (by name)
# OUT (G) mem_la_addr[28] (REP)  =   (R) mem_la_addr[28] (REP) (by name)
# OUT (G) mem_la_addr[27] (REP)  =   (R) mem_la_addr[27] (REP) (by name)
# OUT (G) mem_la_addr[26] (REP)  =   (R) mem_la_addr[26] (REP) (by name)
# OUT (G) mem_la_addr[25] (REP)  =   (R) mem_la_addr[25] (REP) (by name)
# OUT (G) mem_la_addr[24] (REP)  =   (R) mem_la_addr[24] (REP) (by name)
# OUT (G) mem_la_addr[23] (REP)  =   (R) mem_la_addr[23] (REP) (by name)
# OUT (G) mem_la_addr[22] (REP)  =   (R) mem_la_addr[22] (REP) (by name)
# OUT (G) mem_la_addr[21] (REP)  =   (R) mem_la_addr[21] (REP) (by name)
# OUT (G) mem_la_addr[20] (REP)  =   (R) mem_la_addr[20] (REP) (by name)
# OUT (G) mem_la_addr[19] (REP)  =   (R) mem_la_addr[19] (REP) (by name)
# OUT (G) mem_la_addr[18] (REP)  =   (R) mem_la_addr[18] (REP) (by name)
# OUT (G) mem_la_addr[17] (REP)  =   (R) mem_la_addr[17] (REP) (by name)
# OUT (G) mem_la_addr[16] (REP)  =   (R) mem_la_addr[16] (REP) (by name)
# OUT (G) mem_la_addr[15] (REP)  =   (R) mem_la_addr[15] (REP) (by name)
# OUT (G) mem_la_addr[14] (REP)  =   (R) mem_la_addr[14] (REP) (by name)
# OUT (G) mem_la_addr[13] (REP)  =   (R) mem_la_addr[13] (REP) (by name)
# OUT (G) mem_la_addr[12] (REP)  =   (R) mem_la_addr[12] (REP) (by name)
# OUT (G) mem_la_addr[11] (REP)  =   (R) mem_la_addr[11] (REP) (by name)
# OUT (G) mem_la_addr[10] (REP)  =   (R) mem_la_addr[10] (REP) (by name)
# OUT (G) mem_la_addr[9] (REP)  =   (R) mem_la_addr[9] (REP) (by name)
# OUT (G) mem_la_addr[8] (REP)  =   (R) mem_la_addr[8] (REP) (by name)
# OUT (G) mem_la_addr[7] (REP)  =   (R) mem_la_addr[7] (REP) (by name)
# OUT (G) mem_la_addr[6] (REP)  =   (R) mem_la_addr[6] (REP) (by name)
# OUT (G) mem_la_addr[5] (REP)  =   (R) mem_la_addr[5] (REP) (by name)
# OUT (G) mem_la_addr[4] (REP)  =   (R) mem_la_addr[4] (REP) (by name)
# OUT (G) mem_la_addr[3] (REP)  =   (R) mem_la_addr[3] (REP) (by name)
# OUT (G) mem_la_addr[2] (REP)  =   (R) mem_la_addr[2] (REP) (by name)
# OUT (G) mem_la_addr[1] 0(REP)  =   (R) mem_la_addr[1] 0(REP) (by name)
# OUT (G) mem_la_addr[0] 0(REP)  =   (R) mem_la_addr[0] 0(REP) (by name)
# OUT (G) mem_la_wdata[31] (REP)  =   (R) mem_la_wdata[31] (REP) (by name)
# OUT (G) mem_la_wdata[30] (REP)  =   (R) mem_la_wdata[30] (REP) (by name)
# OUT (G) mem_la_wdata[29] (REP)  =   (R) mem_la_wdata[29] (REP) (by name)
# OUT (G) mem_la_wdata[28] (REP)  =   (R) mem_la_wdata[28] (REP) (by name)
# OUT (G) mem_la_wdata[27] (REP)  =   (R) mem_la_wdata[27] (REP) (by name)
# OUT (G) mem_la_wdata[26] (REP)  =   (R) mem_la_wdata[26] (REP) (by name)
# OUT (G) mem_la_wdata[25] (REP)  =   (R) mem_la_wdata[25] (REP) (by name)
# OUT (G) mem_la_wdata[24] (REP)  =   (R) mem_la_wdata[24] (REP) (by name)
# OUT (G) mem_la_wdata[23] (REP)  =   (R) mem_la_wdata[23] (REP) (by name)
# OUT (G) mem_la_wdata[22] (REP)  =   (R) mem_la_wdata[22] (REP) (by name)
# OUT (G) mem_la_wdata[21] (REP)  =   (R) mem_la_wdata[21] (REP) (by name)
# OUT (G) mem_la_wdata[20] (REP)  =   (R) mem_la_wdata[20] (REP) (by name)
# OUT (G) mem_la_wdata[19] (REP)  =   (R) mem_la_wdata[19] (REP) (by name)
# OUT (G) mem_la_wdata[18] (REP)  =   (R) mem_la_wdata[18] (REP) (by name)
# OUT (G) mem_la_wdata[17] (REP)  =   (R) mem_la_wdata[17] (REP) (by name)
# OUT (G) mem_la_wdata[16] (REP)  =   (R) mem_la_wdata[16] (REP) (by name)
# OUT (G) mem_la_wdata[15] (REP)  =   (R) mem_la_wdata[15] (REP) (by name)
# OUT (G) mem_la_wdata[14] (REP)  =   (R) mem_la_wdata[14] (REP) (by name)
# OUT (G) mem_la_wdata[13] (REP)  =   (R) mem_la_wdata[13] (REP) (by name)
# OUT (G) mem_la_wdata[12] (REP)  =   (R) mem_la_wdata[12] (REP) (by name)
# OUT (G) mem_la_wdata[11] (REP)  =   (R) mem_la_wdata[11] (REP) (by name)
# OUT (G) mem_la_wdata[10] (REP)  =   (R) mem_la_wdata[10] (REP) (by name)
# OUT (G) mem_la_wdata[9] (REP)  =   (R) mem_la_wdata[9] (REP) (by name)
# OUT (G) mem_la_wdata[8] (REP)  =   (R) mem_la_wdata[8] (REP) (by name)
# OUT (G) mem_la_wdata[7] (REP)  =   (R) mem_la_wdata[7] (REP) (by name)
# OUT (G) mem_la_wdata[6] (REP)  =   (R) mem_la_wdata[6] (REP) (by name)
# OUT (G) mem_la_wdata[5] (REP)  =   (R) mem_la_wdata[5] (REP) (by name)
# OUT (G) mem_la_wdata[4] (REP)  =   (R) mem_la_wdata[4] (REP) (by name)
# OUT (G) mem_la_wdata[3] (REP)  =   (R) mem_la_wdata[3] (REP) (by name)
# OUT (G) mem_la_wdata[2] (REP)  =   (R) mem_la_wdata[2] (REP) (by name)
# OUT (G) mem_la_wdata[1] (REP)  =   (R) mem_la_wdata[1] (REP) (by name)
# OUT (G) mem_la_wdata[0] (REP)  =   (R) mem_la_wdata[0] (REP) (by name)
# OUT (G) mem_la_wstrb[3] (REP)  =   (R) mem_la_wstrb[3] (REP) (by name)
# OUT (G) mem_la_wstrb[2] (REP)  =   (R) mem_la_wstrb[2] (REP) (by name)
# OUT (G) mem_la_wstrb[1] (REP)  =   (R) mem_la_wstrb[1] (REP) (by name)
# OUT (G) mem_la_wstrb[0] (REP)  =   (R) mem_la_wstrb[0] (REP) (by name)
# OUT (G) pcpi_valid 0(REP)  =   (R) pcpi_valid 0(REP) (by name)
# OUT (G) pcpi_insn[31] 0(REP)  =   (R) pcpi_insn[31] 0(REP) (by name)
# OUT (G) pcpi_insn[30] 0(REP)  =   (R) pcpi_insn[30] 0(REP) (by name)
# OUT (G) pcpi_insn[29] 0(REP)  =   (R) pcpi_insn[29] 0(REP) (by name)
# OUT (G) pcpi_insn[28] 0(REP)  =   (R) pcpi_insn[28] 0(REP) (by name)
# OUT (G) pcpi_insn[27] 0(REP)  =   (R) pcpi_insn[27] 0(REP) (by name)
# OUT (G) pcpi_insn[26] 0(REP)  =   (R) pcpi_insn[26] 0(REP) (by name)
# OUT (G) pcpi_insn[25] 0(REP)  =   (R) pcpi_insn[25] 0(REP) (by name)
# OUT (G) pcpi_insn[24] 0(REP)  =   (R) pcpi_insn[24] 0(REP) (by name)
# OUT (G) pcpi_insn[23] 0(REP)  =   (R) pcpi_insn[23] 0(REP) (by name)
# OUT (G) pcpi_insn[22] 0(REP)  =   (R) pcpi_insn[22] 0(REP) (by name)
# OUT (G) pcpi_insn[21] 0(REP)  =   (R) pcpi_insn[21] 0(REP) (by name)
# OUT (G) pcpi_insn[20] 0(REP)  =   (R) pcpi_insn[20] 0(REP) (by name)
# OUT (G) pcpi_insn[19] 0(REP)  =   (R) pcpi_insn[19] 0(REP) (by name)
# OUT (G) pcpi_insn[18] 0(REP)  =   (R) pcpi_insn[18] 0(REP) (by name)
# OUT (G) pcpi_insn[17] 0(REP)  =   (R) pcpi_insn[17] 0(REP) (by name)
# OUT (G) pcpi_insn[16] 0(REP)  =   (R) pcpi_insn[16] 0(REP) (by name)
# OUT (G) pcpi_insn[15] 0(REP)  =   (R) pcpi_insn[15] 0(REP) (by name)
# OUT (G) pcpi_insn[14] 0(REP)  =   (R) pcpi_insn[14] 0(REP) (by name)
# OUT (G) pcpi_insn[13] 0(REP)  =   (R) pcpi_insn[13] 0(REP) (by name)
# OUT (G) pcpi_insn[12] 0(REP)  =   (R) pcpi_insn[12] 0(REP) (by name)
# OUT (G) pcpi_insn[11] 0(REP)  =   (R) pcpi_insn[11] 0(REP) (by name)
# OUT (G) pcpi_insn[10] 0(REP)  =   (R) pcpi_insn[10] 0(REP) (by name)
# OUT (G) pcpi_insn[9] 0(REP)  =   (R) pcpi_insn[9] 0(REP) (by name)
# OUT (G) pcpi_insn[8] 0(REP)  =   (R) pcpi_insn[8] 0(REP) (by name)
# OUT (G) pcpi_insn[7] 0(REP)  =   (R) pcpi_insn[7] 0(REP) (by name)
# OUT (G) pcpi_insn[6] 0(REP)  =   (R) pcpi_insn[6] 0(REP) (by name)
# OUT (G) pcpi_insn[5] 0(REP)  =   (R) pcpi_insn[5] 0(REP) (by name)
# OUT (G) pcpi_insn[4] 0(REP)  =   (R) pcpi_insn[4] 0(REP) (by name)
# OUT (G) pcpi_insn[3] 0(REP)  =   (R) pcpi_insn[3] 0(REP) (by name)
# OUT (G) pcpi_insn[2] 0(REP)  =   (R) pcpi_insn[2] 0(REP) (by name)
# OUT (G) pcpi_insn[1] 0(REP)  =   (R) pcpi_insn[1] 0(REP) (by name)
# OUT (G) pcpi_insn[0] 0(REP)  =   (R) pcpi_insn[0] 0(REP) (by name)
# OUT (G) pcpi_rs1[31] (REP)  =   (R) pcpi_rs1[31] (REP) (by name)
# OUT (G) pcpi_rs1[30] (REP)  =   (R) pcpi_rs1[30] (REP) (by name)
# OUT (G) pcpi_rs1[29] (REP)  =   (R) pcpi_rs1[29] (REP) (by name)
# OUT (G) pcpi_rs1[28] (REP)  =   (R) pcpi_rs1[28] (REP) (by name)
# OUT (G) pcpi_rs1[27] (REP)  =   (R) pcpi_rs1[27] (REP) (by name)
# OUT (G) pcpi_rs1[26] (REP)  =   (R) pcpi_rs1[26] (REP) (by name)
# OUT (G) pcpi_rs1[25] (REP)  =   (R) pcpi_rs1[25] (REP) (by name)
# OUT (G) pcpi_rs1[24] (REP)  =   (R) pcpi_rs1[24] (REP) (by name)
# OUT (G) pcpi_rs1[23] (REP)  =   (R) pcpi_rs1[23] (REP) (by name)
# OUT (G) pcpi_rs1[22] (REP)  =   (R) pcpi_rs1[22] (REP) (by name)
# OUT (G) pcpi_rs1[21] (REP)  =   (R) pcpi_rs1[21] (REP) (by name)
# OUT (G) pcpi_rs1[20] (REP)  =   (R) pcpi_rs1[20] (REP) (by name)
# OUT (G) pcpi_rs1[19] (REP)  =   (R) pcpi_rs1[19] (REP) (by name)
# OUT (G) pcpi_rs1[18] (REP)  =   (R) pcpi_rs1[18] (REP) (by name)
# OUT (G) pcpi_rs1[17] (REP)  =   (R) pcpi_rs1[17] (REP) (by name)
# OUT (G) pcpi_rs1[16] (REP)  =   (R) pcpi_rs1[16] (REP) (by name)
# OUT (G) pcpi_rs1[15] (REP)  =   (R) pcpi_rs1[15] (REP) (by name)
# OUT (G) pcpi_rs1[14] (REP)  =   (R) pcpi_rs1[14] (REP) (by name)
# OUT (G) pcpi_rs1[13] (REP)  =   (R) pcpi_rs1[13] (REP) (by name)
# OUT (G) pcpi_rs1[12] (REP)  =   (R) pcpi_rs1[12] (REP) (by name)
# OUT (G) pcpi_rs1[11] (REP)  =   (R) pcpi_rs1[11] (REP) (by name)
# OUT (G) pcpi_rs1[10] (REP)  =   (R) pcpi_rs1[10] (REP) (by name)
# OUT (G) pcpi_rs1[9] (REP)  =   (R) pcpi_rs1[9] (REP) (by name)
# OUT (G) pcpi_rs1[8] (REP)  =   (R) pcpi_rs1[8] (REP) (by name)
# OUT (G) pcpi_rs1[7] (REP)  =   (R) pcpi_rs1[7] (REP) (by name)
# OUT (G) pcpi_rs1[6] (REP)  =   (R) pcpi_rs1[6] (REP) (by name)
# OUT (G) pcpi_rs1[5] (REP)  =   (R) pcpi_rs1[5] (REP) (by name)
# OUT (G) pcpi_rs1[4] (REP)  =   (R) pcpi_rs1[4] (REP) (by name)
# OUT (G) pcpi_rs1[3] (REP)  =   (R) pcpi_rs1[3] (REP) (by name)
# OUT (G) pcpi_rs1[2] (REP)  =   (R) pcpi_rs1[2] (REP) (by name)
# OUT (G) pcpi_rs1[1] (REP)  =   (R) pcpi_rs1[1] (REP) (by name)
# OUT (G) pcpi_rs1[0] (REP)  =   (R) pcpi_rs1[0] (REP) (by name)
# OUT (G) pcpi_rs2[31] (REP)  =   (R) pcpi_rs2[31] (REP) (by name)
# OUT (G) pcpi_rs2[30] (REP)  =   (R) pcpi_rs2[30] (REP) (by name)
# OUT (G) pcpi_rs2[29] (REP)  =   (R) pcpi_rs2[29] (REP) (by name)
# OUT (G) pcpi_rs2[28] (REP)  =   (R) pcpi_rs2[28] (REP) (by name)
# OUT (G) pcpi_rs2[27] (REP)  =   (R) pcpi_rs2[27] (REP) (by name)
# OUT (G) pcpi_rs2[26] (REP)  =   (R) pcpi_rs2[26] (REP) (by name)
# OUT (G) pcpi_rs2[25] (REP)  =   (R) pcpi_rs2[25] (REP) (by name)
# OUT (G) pcpi_rs2[24] (REP)  =   (R) pcpi_rs2[24] (REP) (by name)
# OUT (G) pcpi_rs2[23] (REP)  =   (R) pcpi_rs2[23] (REP) (by name)
# OUT (G) pcpi_rs2[22] (REP)  =   (R) pcpi_rs2[22] (REP) (by name)
# OUT (G) pcpi_rs2[21] (REP)  =   (R) pcpi_rs2[21] (REP) (by name)
# OUT (G) pcpi_rs2[20] (REP)  =   (R) pcpi_rs2[20] (REP) (by name)
# OUT (G) pcpi_rs2[19] (REP)  =   (R) pcpi_rs2[19] (REP) (by name)
# OUT (G) pcpi_rs2[18] (REP)  =   (R) pcpi_rs2[18] (REP) (by name)
# OUT (G) pcpi_rs2[17] (REP)  =   (R) pcpi_rs2[17] (REP) (by name)
# OUT (G) pcpi_rs2[16] (REP)  =   (R) pcpi_rs2[16] (REP) (by name)
# OUT (G) pcpi_rs2[15] (REP)  =   (R) pcpi_rs2[15] (REP) (by name)
# OUT (G) pcpi_rs2[14] (REP)  =   (R) pcpi_rs2[14] (REP) (by name)
# OUT (G) pcpi_rs2[13] (REP)  =   (R) pcpi_rs2[13] (REP) (by name)
# OUT (G) pcpi_rs2[12] (REP)  =   (R) pcpi_rs2[12] (REP) (by name)
# OUT (G) pcpi_rs2[11] (REP)  =   (R) pcpi_rs2[11] (REP) (by name)
# OUT (G) pcpi_rs2[10] (REP)  =   (R) pcpi_rs2[10] (REP) (by name)
# OUT (G) pcpi_rs2[9] (REP)  =   (R) pcpi_rs2[9] (REP) (by name)
# OUT (G) pcpi_rs2[8] (REP)  =   (R) pcpi_rs2[8] (REP) (by name)
# OUT (G) pcpi_rs2[7] (REP)  =   (R) pcpi_rs2[7] (REP) (by name)
# OUT (G) pcpi_rs2[6] (REP)  =   (R) pcpi_rs2[6] (REP) (by name)
# OUT (G) pcpi_rs2[5] (REP)  =   (R) pcpi_rs2[5] (REP) (by name)
# OUT (G) pcpi_rs2[4] (REP)  =   (R) pcpi_rs2[4] (REP) (by name)
# OUT (G) pcpi_rs2[3] (REP)  =   (R) pcpi_rs2[3] (REP) (by name)
# OUT (G) pcpi_rs2[2] (REP)  =   (R) pcpi_rs2[2] (REP) (by name)
# OUT (G) pcpi_rs2[1] (REP)  =   (R) pcpi_rs2[1] (REP) (by name)
# OUT (G) pcpi_rs2[0] (REP)  =   (R) pcpi_rs2[0] (REP) (by name)
# OUT (G) eoi[31] 0(REP)  =   (R) eoi[31] 0(REP) (by name)
# OUT (G) eoi[30] 0(REP)  =   (R) eoi[30] 0(REP) (by name)
# OUT (G) eoi[29] 0(REP)  =   (R) eoi[29] 0(REP) (by name)
# OUT (G) eoi[28] 0(REP)  =   (R) eoi[28] 0(REP) (by name)
# OUT (G) eoi[27] 0(REP)  =   (R) eoi[27] 0(REP) (by name)
# OUT (G) eoi[26] 0(REP)  =   (R) eoi[26] 0(REP) (by name)
# OUT (G) eoi[25] 0(REP)  =   (R) eoi[25] 0(REP) (by name)
# OUT (G) eoi[24] 0(REP)  =   (R) eoi[24] 0(REP) (by name)
# OUT (G) eoi[23] 0(REP)  =   (R) eoi[23] 0(REP) (by name)
# OUT (G) eoi[22] 0(REP)  =   (R) eoi[22] 0(REP) (by name)
# OUT (G) eoi[21] 0(REP)  =   (R) eoi[21] 0(REP) (by name)
# OUT (G) eoi[20] 0(REP)  =   (R) eoi[20] 0(REP) (by name)
# OUT (G) eoi[19] 0(REP)  =   (R) eoi[19] 0(REP) (by name)
# OUT (G) eoi[18] 0(REP)  =   (R) eoi[18] 0(REP) (by name)
# OUT (G) eoi[17] 0(REP)  =   (R) eoi[17] 0(REP) (by name)
# OUT (G) eoi[16] 0(REP)  =   (R) eoi[16] 0(REP) (by name)
# OUT (G) eoi[15] 0(REP)  =   (R) eoi[15] 0(REP) (by name)
# OUT (G) eoi[14] 0(REP)  =   (R) eoi[14] 0(REP) (by name)
# OUT (G) eoi[13] 0(REP)  =   (R) eoi[13] 0(REP) (by name)
# OUT (G) eoi[12] 0(REP)  =   (R) eoi[12] 0(REP) (by name)
# OUT (G) eoi[11] 0(REP)  =   (R) eoi[11] 0(REP) (by name)
# OUT (G) eoi[10] 0(REP)  =   (R) eoi[10] 0(REP) (by name)
# OUT (G) eoi[9] 0(REP)  =   (R) eoi[9] 0(REP) (by name)
# OUT (G) eoi[8] 0(REP)  =   (R) eoi[8] 0(REP) (by name)
# OUT (G) eoi[7] 0(REP)  =   (R) eoi[7] 0(REP) (by name)
# OUT (G) eoi[6] 0(REP)  =   (R) eoi[6] 0(REP) (by name)
# OUT (G) eoi[5] 0(REP)  =   (R) eoi[5] 0(REP) (by name)
# OUT (G) eoi[4] 0(REP)  =   (R) eoi[4] 0(REP) (by name)
# OUT (G) eoi[3] 0(REP)  =   (R) eoi[3] 0(REP) (by name)
# OUT (G) eoi[2] 0(REP)  =   (R) eoi[2] 0(REP) (by name)
# OUT (G) eoi[1] 0(REP)  =   (R) eoi[1] 0(REP) (by name)
# OUT (G) eoi[0] 0(REP)  =   (R) eoi[0] 0(REP) (by name)
# OUT (G) trace_valid 0(REP)  =   (R) trace_valid 0(REP) (by name)
# OUT (G) trace_data[35] 0(REP)  =   (R) trace_data[35] 0(REP) (by name)
# OUT (G) trace_data[34] 0(REP)  =   (R) trace_data[34] 0(REP) (by name)
# OUT (G) trace_data[33] 0(REP)  =   (R) trace_data[33] 0(REP) (by name)
# OUT (G) trace_data[32] 0(REP)  =   (R) trace_data[32] 0(REP) (by name)
# OUT (G) trace_data[31] 0(REP)  =   (R) trace_data[31] 0(REP) (by name)
# OUT (G) trace_data[30] 0(REP)  =   (R) trace_data[30] 0(REP) (by name)
# OUT (G) trace_data[29] 0(REP)  =   (R) trace_data[29] 0(REP) (by name)
# OUT (G) trace_data[28] 0(REP)  =   (R) trace_data[28] 0(REP) (by name)
# OUT (G) trace_data[27] 0(REP)  =   (R) trace_data[27] 0(REP) (by name)
# OUT (G) trace_data[26] 0(REP)  =   (R) trace_data[26] 0(REP) (by name)
# OUT (G) trace_data[25] 0(REP)  =   (R) trace_data[25] 0(REP) (by name)
# OUT (G) trace_data[24] 0(REP)  =   (R) trace_data[24] 0(REP) (by name)
# OUT (G) trace_data[23] 0(REP)  =   (R) trace_data[23] 0(REP) (by name)
# OUT (G) trace_data[22] 0(REP)  =   (R) trace_data[22] 0(REP) (by name)
# OUT (G) trace_data[21] 0(REP)  =   (R) trace_data[21] 0(REP) (by name)
# OUT (G) trace_data[20] 0(REP)  =   (R) trace_data[20] 0(REP) (by name)
# OUT (G) trace_data[19] 0(REP)  =   (R) trace_data[19] 0(REP) (by name)
# OUT (G) trace_data[18] 0(REP)  =   (R) trace_data[18] 0(REP) (by name)
# OUT (G) trace_data[17] 0(REP)  =   (R) trace_data[17] 0(REP) (by name)
# OUT (G) trace_data[16] 0(REP)  =   (R) trace_data[16] 0(REP) (by name)
# OUT (G) trace_data[15] 0(REP)  =   (R) trace_data[15] 0(REP) (by name)
# OUT (G) trace_data[14] 0(REP)  =   (R) trace_data[14] 0(REP) (by name)
# OUT (G) trace_data[13] 0(REP)  =   (R) trace_data[13] 0(REP) (by name)
# OUT (G) trace_data[12] 0(REP)  =   (R) trace_data[12] 0(REP) (by name)
# OUT (G) trace_data[11] 0(REP)  =   (R) trace_data[11] 0(REP) (by name)
# OUT (G) trace_data[10] 0(REP)  =   (R) trace_data[10] 0(REP) (by name)
# OUT (G) trace_data[9] 0(REP)  =   (R) trace_data[9] 0(REP) (by name)
# OUT (G) trace_data[8] 0(REP)  =   (R) trace_data[8] 0(REP) (by name)
# OUT (G) trace_data[7] 0(REP)  =   (R) trace_data[7] 0(REP) (by name)
# OUT (G) trace_data[6] 0(REP)  =   (R) trace_data[6] 0(REP) (by name)
# OUT (G) trace_data[5] 0(REP)  =   (R) trace_data[5] 0(REP) (by name)
# OUT (G) trace_data[4] 0(REP)  =   (R) trace_data[4] 0(REP) (by name)
# OUT (G) trace_data[3] 0(REP)  =   (R) trace_data[3] 0(REP) (by name)
# OUT (G) trace_data[2] 0(REP)  =   (R) trace_data[2] 0(REP) (by name)
# OUT (G) trace_data[1] 0(REP)  =   (R) trace_data[1] 0(REP) (by name)
# OUT (G) trace_data[0] 0(REP)  =   (R) trace_data[0] 0(REP) (by name)
set_root_module picorv32 -Golden
set_root_module picorv32 -Revised
set_module_property -instance / -Golden
set_module_property -instance / -Revised
# Constraint commands 
add_ignored_inputs pcpi_wr -Golden
# UR
add_ignored_inputs {pcpi_rd[31]} -Golden
# UR
add_ignored_inputs {pcpi_rd[30]} -Golden
# UR
add_ignored_inputs {pcpi_rd[29]} -Golden
# UR
add_ignored_inputs {pcpi_rd[28]} -Golden
# UR
add_ignored_inputs {pcpi_rd[27]} -Golden
# UR
add_ignored_inputs {pcpi_rd[26]} -Golden
# UR
add_ignored_inputs {pcpi_rd[25]} -Golden
# UR
add_ignored_inputs {pcpi_rd[24]} -Golden
# UR
add_ignored_inputs {pcpi_rd[23]} -Golden
# UR
add_ignored_inputs {pcpi_rd[22]} -Golden
# UR
add_ignored_inputs {pcpi_rd[21]} -Golden
# UR
add_ignored_inputs {pcpi_rd[20]} -Golden
# UR
add_ignored_inputs {pcpi_rd[19]} -Golden
# UR
add_ignored_inputs {pcpi_rd[18]} -Golden
# UR
add_ignored_inputs {pcpi_rd[17]} -Golden
# UR
add_ignored_inputs {pcpi_rd[16]} -Golden
# UR
add_ignored_inputs {pcpi_rd[15]} -Golden
# UR
add_ignored_inputs {pcpi_rd[14]} -Golden
# UR
add_ignored_inputs {pcpi_rd[13]} -Golden
# UR
add_ignored_inputs {pcpi_rd[12]} -Golden
# UR
add_ignored_inputs {pcpi_rd[11]} -Golden
# UR
add_ignored_inputs {pcpi_rd[10]} -Golden
# UR
add_ignored_inputs {pcpi_rd[9]} -Golden
# UR
add_ignored_inputs {pcpi_rd[8]} -Golden
# UR
add_ignored_inputs {pcpi_rd[7]} -Golden
# UR
add_ignored_inputs {pcpi_rd[6]} -Golden
# UR
add_ignored_inputs {pcpi_rd[5]} -Golden
# UR
add_ignored_inputs {pcpi_rd[4]} -Golden
# UR
add_ignored_inputs {pcpi_rd[3]} -Golden
# UR
add_ignored_inputs {pcpi_rd[2]} -Golden
# UR
add_ignored_inputs {pcpi_rd[1]} -Golden
# UR
add_ignored_inputs {pcpi_rd[0]} -Golden
# UR
add_ignored_inputs pcpi_wait -Golden
# UR
add_ignored_inputs pcpi_ready -Golden
# UR
add_ignored_inputs {irq[31]} -Golden
# UR
add_ignored_inputs {irq[30]} -Golden
# UR
add_ignored_inputs {irq[29]} -Golden
# UR
add_ignored_inputs {irq[28]} -Golden
# UR
add_ignored_inputs {irq[27]} -Golden
# UR
add_ignored_inputs {irq[26]} -Golden
# UR
add_ignored_inputs {irq[25]} -Golden
# UR
add_ignored_inputs {irq[24]} -Golden
# UR
add_ignored_inputs {irq[23]} -Golden
# UR
add_ignored_inputs {irq[22]} -Golden
# UR
add_ignored_inputs {irq[21]} -Golden
# UR
add_ignored_inputs {irq[20]} -Golden
# UR
add_ignored_inputs {irq[19]} -Golden
# UR
add_ignored_inputs {irq[18]} -Golden
# UR
add_ignored_inputs {irq[17]} -Golden
# UR
add_ignored_inputs {irq[16]} -Golden
# UR
add_ignored_inputs {irq[15]} -Golden
# UR
add_ignored_inputs {irq[14]} -Golden
# UR
add_ignored_inputs {irq[13]} -Golden
# UR
add_ignored_inputs {irq[12]} -Golden
# UR
add_ignored_inputs {irq[11]} -Golden
# UR
add_ignored_inputs {irq[10]} -Golden
# UR
add_ignored_inputs {irq[9]} -Golden
# UR
add_ignored_inputs {irq[8]} -Golden
# UR
add_ignored_inputs {irq[7]} -Golden
# UR
add_ignored_inputs {irq[6]} -Golden
# UR
add_ignored_inputs {irq[5]} -Golden
# UR
add_ignored_inputs {irq[4]} -Golden
# UR
add_ignored_inputs {irq[3]} -Golden
# UR
add_ignored_inputs {irq[2]} -Golden
# UR
add_ignored_inputs {irq[1]} -Golden
# UR
add_ignored_inputs {irq[0]} -Golden
# UR
add_output_stuck_at 0 {mem_addr[1]} -Golden -hier
add_output_stuck_at 0 {mem_addr[0]} -Golden -hier
add_output_stuck_at 0 {mem_la_addr[1]} -Golden -hier
add_output_stuck_at 0 {mem_la_addr[0]} -Golden -hier
add_output_stuck_at 0 pcpi_valid -Golden -hier
add_output_stuck_at 0 {pcpi_insn[31]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[30]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[29]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[28]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[27]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[26]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[25]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[24]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[23]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[22]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[21]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[20]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[19]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[18]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[17]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[16]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[15]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[14]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[13]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[12]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[11]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[10]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[9]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[8]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[7]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[6]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[5]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[4]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[3]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[2]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[1]} -Golden -hier
add_output_stuck_at 0 {pcpi_insn[0]} -Golden -hier
add_output_stuck_at 0 {eoi[31]} -Golden -hier
add_output_stuck_at 0 {eoi[30]} -Golden -hier
add_output_stuck_at 0 {eoi[29]} -Golden -hier
add_output_stuck_at 0 {eoi[28]} -Golden -hier
add_output_stuck_at 0 {eoi[27]} -Golden -hier
add_output_stuck_at 0 {eoi[26]} -Golden -hier
add_output_stuck_at 0 {eoi[25]} -Golden -hier
add_output_stuck_at 0 {eoi[24]} -Golden -hier
add_output_stuck_at 0 {eoi[23]} -Golden -hier
add_output_stuck_at 0 {eoi[22]} -Golden -hier
add_output_stuck_at 0 {eoi[21]} -Golden -hier
add_output_stuck_at 0 {eoi[20]} -Golden -hier
add_output_stuck_at 0 {eoi[19]} -Golden -hier
add_output_stuck_at 0 {eoi[18]} -Golden -hier
add_output_stuck_at 0 {eoi[17]} -Golden -hier
add_output_stuck_at 0 {eoi[16]} -Golden -hier
add_output_stuck_at 0 {eoi[15]} -Golden -hier
add_output_stuck_at 0 {eoi[14]} -Golden -hier
add_output_stuck_at 0 {eoi[13]} -Golden -hier
add_output_stuck_at 0 {eoi[12]} -Golden -hier
add_output_stuck_at 0 {eoi[11]} -Golden -hier
add_output_stuck_at 0 {eoi[10]} -Golden -hier
add_output_stuck_at 0 {eoi[9]} -Golden -hier
add_output_stuck_at 0 {eoi[8]} -Golden -hier
add_output_stuck_at 0 {eoi[7]} -Golden -hier
add_output_stuck_at 0 {eoi[6]} -Golden -hier
add_output_stuck_at 0 {eoi[5]} -Golden -hier
add_output_stuck_at 0 {eoi[4]} -Golden -hier
add_output_stuck_at 0 {eoi[3]} -Golden -hier
add_output_stuck_at 0 {eoi[2]} -Golden -hier
add_output_stuck_at 0 {eoi[1]} -Golden -hier
add_output_stuck_at 0 {eoi[0]} -Golden -hier
add_output_stuck_at 0 trace_valid -Golden -hier
add_output_stuck_at 0 {trace_data[35]} -Golden -hier
add_output_stuck_at 0 {trace_data[34]} -Golden -hier
add_output_stuck_at 0 {trace_data[33]} -Golden -hier
add_output_stuck_at 0 {trace_data[32]} -Golden -hier
add_output_stuck_at 0 {trace_data[31]} -Golden -hier
add_output_stuck_at 0 {trace_data[30]} -Golden -hier
add_output_stuck_at 0 {trace_data[29]} -Golden -hier
add_output_stuck_at 0 {trace_data[28]} -Golden -hier
add_output_stuck_at 0 {trace_data[27]} -Golden -hier
add_output_stuck_at 0 {trace_data[26]} -Golden -hier
add_output_stuck_at 0 {trace_data[25]} -Golden -hier
add_output_stuck_at 0 {trace_data[24]} -Golden -hier
add_output_stuck_at 0 {trace_data[23]} -Golden -hier
add_output_stuck_at 0 {trace_data[22]} -Golden -hier
add_output_stuck_at 0 {trace_data[21]} -Golden -hier
add_output_stuck_at 0 {trace_data[20]} -Golden -hier
add_output_stuck_at 0 {trace_data[19]} -Golden -hier
add_output_stuck_at 0 {trace_data[18]} -Golden -hier
add_output_stuck_at 0 {trace_data[17]} -Golden -hier
add_output_stuck_at 0 {trace_data[16]} -Golden -hier
add_output_stuck_at 0 {trace_data[15]} -Golden -hier
add_output_stuck_at 0 {trace_data[14]} -Golden -hier
add_output_stuck_at 0 {trace_data[13]} -Golden -hier
add_output_stuck_at 0 {trace_data[12]} -Golden -hier
add_output_stuck_at 0 {trace_data[11]} -Golden -hier
add_output_stuck_at 0 {trace_data[10]} -Golden -hier
add_output_stuck_at 0 {trace_data[9]} -Golden -hier
add_output_stuck_at 0 {trace_data[8]} -Golden -hier
add_output_stuck_at 0 {trace_data[7]} -Golden -hier
add_output_stuck_at 0 {trace_data[6]} -Golden -hier
add_output_stuck_at 0 {trace_data[5]} -Golden -hier
add_output_stuck_at 0 {trace_data[4]} -Golden -hier
add_output_stuck_at 0 {trace_data[3]} -Golden -hier
add_output_stuck_at 0 {trace_data[2]} -Golden -hier
add_output_stuck_at 0 {trace_data[1]} -Golden -hier
add_output_stuck_at 0 {trace_data[0]} -Golden -hier
add_ignored_inputs pcpi_wr -Revised
# UR
add_ignored_inputs {pcpi_rd[31]} -Revised
# UR
add_ignored_inputs {pcpi_rd[30]} -Revised
# UR
add_ignored_inputs {pcpi_rd[29]} -Revised
# UR
add_ignored_inputs {pcpi_rd[28]} -Revised
# UR
add_ignored_inputs {pcpi_rd[27]} -Revised
# UR
add_ignored_inputs {pcpi_rd[26]} -Revised
# UR
add_ignored_inputs {pcpi_rd[25]} -Revised
# UR
add_ignored_inputs {pcpi_rd[24]} -Revised
# UR
add_ignored_inputs {pcpi_rd[23]} -Revised
# UR
add_ignored_inputs {pcpi_rd[22]} -Revised
# UR
add_ignored_inputs {pcpi_rd[21]} -Revised
# UR
add_ignored_inputs {pcpi_rd[20]} -Revised
# UR
add_ignored_inputs {pcpi_rd[19]} -Revised
# UR
add_ignored_inputs {pcpi_rd[18]} -Revised
# UR
add_ignored_inputs {pcpi_rd[17]} -Revised
# UR
add_ignored_inputs {pcpi_rd[16]} -Revised
# UR
add_ignored_inputs {pcpi_rd[15]} -Revised
# UR
add_ignored_inputs {pcpi_rd[14]} -Revised
# UR
add_ignored_inputs {pcpi_rd[13]} -Revised
# UR
add_ignored_inputs {pcpi_rd[12]} -Revised
# UR
add_ignored_inputs {pcpi_rd[11]} -Revised
# UR
add_ignored_inputs {pcpi_rd[10]} -Revised
# UR
add_ignored_inputs {pcpi_rd[9]} -Revised
# UR
add_ignored_inputs {pcpi_rd[8]} -Revised
# UR
add_ignored_inputs {pcpi_rd[7]} -Revised
# UR
add_ignored_inputs {pcpi_rd[6]} -Revised
# UR
add_ignored_inputs {pcpi_rd[5]} -Revised
# UR
add_ignored_inputs {pcpi_rd[4]} -Revised
# UR
add_ignored_inputs {pcpi_rd[3]} -Revised
# UR
add_ignored_inputs {pcpi_rd[2]} -Revised
# UR
add_ignored_inputs {pcpi_rd[1]} -Revised
# UR
add_ignored_inputs {pcpi_rd[0]} -Revised
# UR
add_ignored_inputs pcpi_wait -Revised
# UR
add_ignored_inputs pcpi_ready -Revised
# UR
add_ignored_inputs {irq[31]} -Revised
# UR
add_ignored_inputs {irq[30]} -Revised
# UR
add_ignored_inputs {irq[29]} -Revised
# UR
add_ignored_inputs {irq[28]} -Revised
# UR
add_ignored_inputs {irq[27]} -Revised
# UR
add_ignored_inputs {irq[26]} -Revised
# UR
add_ignored_inputs {irq[25]} -Revised
# UR
add_ignored_inputs {irq[24]} -Revised
# UR
add_ignored_inputs {irq[23]} -Revised
# UR
add_ignored_inputs {irq[22]} -Revised
# UR
add_ignored_inputs {irq[21]} -Revised
# UR
add_ignored_inputs {irq[20]} -Revised
# UR
add_ignored_inputs {irq[19]} -Revised
# UR
add_ignored_inputs {irq[18]} -Revised
# UR
add_ignored_inputs {irq[17]} -Revised
# UR
add_ignored_inputs {irq[16]} -Revised
# UR
add_ignored_inputs {irq[15]} -Revised
# UR
add_ignored_inputs {irq[14]} -Revised
# UR
add_ignored_inputs {irq[13]} -Revised
# UR
add_ignored_inputs {irq[12]} -Revised
# UR
add_ignored_inputs {irq[11]} -Revised
# UR
add_ignored_inputs {irq[10]} -Revised
# UR
add_ignored_inputs {irq[9]} -Revised
# UR
add_ignored_inputs {irq[8]} -Revised
# UR
add_ignored_inputs {irq[7]} -Revised
# UR
add_ignored_inputs {irq[6]} -Revised
# UR
add_ignored_inputs {irq[5]} -Revised
# UR
add_ignored_inputs {irq[4]} -Revised
# UR
add_ignored_inputs {irq[3]} -Revised
# UR
add_ignored_inputs {irq[2]} -Revised
# UR
add_ignored_inputs {irq[1]} -Revised
# UR
add_ignored_inputs {irq[0]} -Revised
# UR
add_output_stuck_at 0 {mem_addr[1]} -Revised -hier
add_output_stuck_at 0 {mem_addr[0]} -Revised -hier
add_output_stuck_at 0 {mem_la_addr[1]} -Revised -hier
add_output_stuck_at 0 {mem_la_addr[0]} -Revised -hier
add_output_stuck_at 0 pcpi_valid -Revised -hier
add_output_stuck_at 0 {pcpi_insn[31]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[30]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[29]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[28]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[27]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[26]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[25]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[24]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[23]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[22]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[21]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[20]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[19]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[18]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[17]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[16]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[15]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[14]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[13]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[12]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[11]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[10]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[9]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[8]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[7]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[6]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[5]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[4]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[3]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[2]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[1]} -Revised -hier
add_output_stuck_at 0 {pcpi_insn[0]} -Revised -hier
add_output_stuck_at 0 {eoi[31]} -Revised -hier
add_output_stuck_at 0 {eoi[30]} -Revised -hier
add_output_stuck_at 0 {eoi[29]} -Revised -hier
add_output_stuck_at 0 {eoi[28]} -Revised -hier
add_output_stuck_at 0 {eoi[27]} -Revised -hier
add_output_stuck_at 0 {eoi[26]} -Revised -hier
add_output_stuck_at 0 {eoi[25]} -Revised -hier
add_output_stuck_at 0 {eoi[24]} -Revised -hier
add_output_stuck_at 0 {eoi[23]} -Revised -hier
add_output_stuck_at 0 {eoi[22]} -Revised -hier
add_output_stuck_at 0 {eoi[21]} -Revised -hier
add_output_stuck_at 0 {eoi[20]} -Revised -hier
add_output_stuck_at 0 {eoi[19]} -Revised -hier
add_output_stuck_at 0 {eoi[18]} -Revised -hier
add_output_stuck_at 0 {eoi[17]} -Revised -hier
add_output_stuck_at 0 {eoi[16]} -Revised -hier
add_output_stuck_at 0 {eoi[15]} -Revised -hier
add_output_stuck_at 0 {eoi[14]} -Revised -hier
add_output_stuck_at 0 {eoi[13]} -Revised -hier
add_output_stuck_at 0 {eoi[12]} -Revised -hier
add_output_stuck_at 0 {eoi[11]} -Revised -hier
add_output_stuck_at 0 {eoi[10]} -Revised -hier
add_output_stuck_at 0 {eoi[9]} -Revised -hier
add_output_stuck_at 0 {eoi[8]} -Revised -hier
add_output_stuck_at 0 {eoi[7]} -Revised -hier
add_output_stuck_at 0 {eoi[6]} -Revised -hier
add_output_stuck_at 0 {eoi[5]} -Revised -hier
add_output_stuck_at 0 {eoi[4]} -Revised -hier
add_output_stuck_at 0 {eoi[3]} -Revised -hier
add_output_stuck_at 0 {eoi[2]} -Revised -hier
add_output_stuck_at 0 {eoi[1]} -Revised -hier
add_output_stuck_at 0 {eoi[0]} -Revised -hier
add_output_stuck_at 0 trace_valid -Revised -hier
add_output_stuck_at 0 {trace_data[35]} -Revised -hier
add_output_stuck_at 0 {trace_data[34]} -Revised -hier
add_output_stuck_at 0 {trace_data[33]} -Revised -hier
add_output_stuck_at 0 {trace_data[32]} -Revised -hier
add_output_stuck_at 0 {trace_data[31]} -Revised -hier
add_output_stuck_at 0 {trace_data[30]} -Revised -hier
add_output_stuck_at 0 {trace_data[29]} -Revised -hier
add_output_stuck_at 0 {trace_data[28]} -Revised -hier
add_output_stuck_at 0 {trace_data[27]} -Revised -hier
add_output_stuck_at 0 {trace_data[26]} -Revised -hier
add_output_stuck_at 0 {trace_data[25]} -Revised -hier
add_output_stuck_at 0 {trace_data[24]} -Revised -hier
add_output_stuck_at 0 {trace_data[23]} -Revised -hier
add_output_stuck_at 0 {trace_data[22]} -Revised -hier
add_output_stuck_at 0 {trace_data[21]} -Revised -hier
add_output_stuck_at 0 {trace_data[20]} -Revised -hier
add_output_stuck_at 0 {trace_data[19]} -Revised -hier
add_output_stuck_at 0 {trace_data[18]} -Revised -hier
add_output_stuck_at 0 {trace_data[17]} -Revised -hier
add_output_stuck_at 0 {trace_data[16]} -Revised -hier
add_output_stuck_at 0 {trace_data[15]} -Revised -hier
add_output_stuck_at 0 {trace_data[14]} -Revised -hier
add_output_stuck_at 0 {trace_data[13]} -Revised -hier
add_output_stuck_at 0 {trace_data[12]} -Revised -hier
add_output_stuck_at 0 {trace_data[11]} -Revised -hier
add_output_stuck_at 0 {trace_data[10]} -Revised -hier
add_output_stuck_at 0 {trace_data[9]} -Revised -hier
add_output_stuck_at 0 {trace_data[8]} -Revised -hier
add_output_stuck_at 0 {trace_data[7]} -Revised -hier
add_output_stuck_at 0 {trace_data[6]} -Revised -hier
add_output_stuck_at 0 {trace_data[5]} -Revised -hier
add_output_stuck_at 0 {trace_data[4]} -Revised -hier
add_output_stuck_at 0 {trace_data[3]} -Revised -hier
add_output_stuck_at 0 {trace_data[2]} -Revised -hier
add_output_stuck_at 0 {trace_data[1]} -Revised -hier
add_output_stuck_at 0 {trace_data[0]} -Revised -hier
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose ; eval analyze_datapath -flowgraph -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
usage
report_hier_compare_result
report_hier_compare_result -Nonequivalent
report_hier_compare_result -Abort
report_hier_compare_result -Uncompared
#-------------------------------------------------------------------------------
# VERBOSE REPORTING
#-------------------------------------------------------------------------------
# _END_OF_LEC_HIERARCHICAL_DOFILE_
