tclmode

# Generated by Genus(TM) Synthesis Solution 19.13-s073_1, revision 1.407f
# Generated on: Sun Jan 11 16:11:56 IST 2026 (Sun Jan 11 10:41:56 GMT 2026)

set_screen_display -noprogress
set_dofile_abort exit

# Turns on the flowgraph datapath solver.
set wlec_analyze_dp_flowgraph true
# Indicates that resource sharing datapath optimization is present.
set share_dp_analysis         false

set lec_version [regsub {(-)[A-Za-z]} $env(LEC_VERSION) ""]

# The flowgraph solver is recommended for datapath analysis in LEC 19.1 or newer.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required &&
    $wlec_analyze_dp_flowgraph} {
    set DATAPATH_SOLVER_OPTION "-flowgraph"
} elseif {$share_dp_analysis} {
    set DATAPATH_SOLVER_OPTION "-share"
} else {
    set DATAPATH_SOLVER_OPTION ""
}

tcl_set_command_name_echo on

set_log_file lec_dft.log -replace

usage -auto -elapse

set_verification_information write_lec_generate_label.1_dft_netlistv_db

# There was no constraint or implementation information known for the
# golden design when the dofile was generated.
# The constraints and information from the revised design are being
# used for the golden design.
# This may cause incorrect verification results.
#
# Skipping since the implementation information used is the same for
# both designs.
#read_implementation_information fv/picorv32 -golden write_lec_generate_label.1 -revised dft_netlistv

# Root attribute 'wlec_multithread_license_list' can be used to specify a license list
# for multithreaded processing. The default list is used otherwise.
set_parallel_option -threads 1,4 -norelease_license
set_compare_options -threads 1,4

set env(RC_VERSION)     "19.13-s073_1"
set env(CDN_SYNTH_ROOT) "/cadence/GENUS191/tools.lnx86"
set CDN_SYNTH_ROOT      "/cadence/GENUS191/tools.lnx86"
set env(CW_DIR) "/cadence/GENUS191/tools.lnx86/lib/chipware"
set CW_DIR      "/cadence/GENUS191/tools.lnx86/lib/chipware"

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_search_path . /cadence/GENUS191/tools.lnx86/lib/tech -library -both
read_library -liberty -both /home/arpit23132/Desktop/RISCV_Final/slow.lib

read_design -verilog95   -golden -lastmod -noelab final.v
elaborate_design -golden -root {picorv32}

read_design -verilog95   -revised -lastmod -noelab dft_netlist.v
elaborate_design -revised -root {picorv32}

#add_name_alias fv/picorv32/dft_netlistv.singlebit.original_name.alias.json.gz -golden
#set_mapping_method -alias -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge

#add_name_alias fv/picorv32/dft_netlistv.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg((\\\[%w\\\])*(/U\\\$%d)*)$ @1 -type dff dlat -both

# Table of test_signals and related attributes
#
# Index  Pin                            Type             Dedicated  Has_fanout  Port/Pin    special test function      Dft_auto_created      User_defined  LEC_value                      
#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  
#  1      test_mode                      test_mode        true       false       port        none                       true                  true          auto       
#  2      shift_en                       shift_enable     true       false       port        none                       true                  true          auto       
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------  
# Warning : Multiple pin constraints are added to the revised design.
#          The constraints needed to disable test mode are not trivial.
#          It is possible that some valid functional modes will be excluded
#          from the formal verification process.
#          Please review the constraints to ensure they are all expected
#          and appropriate.
add_pin_constraints 0 {test_mode} -golden
add_pin_constraints 0 {shift_en} -golden
add_ignored_outputs {DFT_sdo_1} -golden
add_pin_constraints 0 {test_mode} -revised
add_pin_constraints 0 {shift_en} -revised
add_ignored_outputs {DFT_sdo_1} -revised

set_analyze_option -auto -report_map

set_system_mode lec
report_unmapped_points -summary
report_unmapped_points -notmapped
add_compared_points -all
compare

report_compare_data -class nonequivalent -class abort -class notcompared
report_verification -verbose
report_statistics

write_verification_information
report_verification_information

# Reports how effective the implementation information was.
# This command is only available with LEC 18.20-d330 or later.
set lec_version_required "18.20330"
if {$lec_version >= $lec_version_required} {
#    report_implementation_information
}

puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}

# Generate a detailed summary of the run.
# This command is available with LEC 19.10-p100 or later.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required} {
    analyze_results -logfiles lec_dft.log
}

vpxmode

exit -f
